[build]
  publish = "/public"
  command = "npm run build"
  environment = { NODE_VERSION = "20" }

[[headers]]

  for = "/*"

  [headers.values]
    X-Content-Type-Options = "nosniff"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin"
    Cross-Origin-Resource-Policy = "same-origin"
    Content-Security-Policy = """
      default-src 'none';
      style-src 'self';
      script-src 'self';
      img-src 'self';
      font-src 'self';
      manifest-src 'self';
      connect-src 'self';
      frame-ancestors 'none';
      base-uri 'self';
      form-action 'none'
    """
    Permissions-Policy = """
      camera=(),
      microphone=(),
      payment=(),
      geolocation=()
    """
